package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Applicationable 
type Applicationable interface {
    DirectoryObjectable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetApi()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetAppId()(*string)
    GetAppManagementPolicies()([]AppManagementPolicyable)
    GetAppRoles()([]AppRoleable)
    GetCertification()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetConnectorGroup()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetCreatedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCreatedOnBehalfOf()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetDefaultRedirectUri()(*string)
    GetDescription()(*string)
    GetDisabledByMicrosoftStatus()(*string)
    GetDisplayName()(*string)
    GetExtensionProperties()([]ExtensionPropertyable)
    GetFederatedIdentityCredentials()([]FederatedIdentityCredentialable)
    GetGroupMembershipClaims()(*string)
    GetHomeRealmDiscoveryPolicies()([]HomeRealmDiscoveryPolicyable)
    GetIdentifierUris()([]string)
    GetInfo()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetIsDeviceOnlyAuthSupported()(*bool)
    GetIsFallbackPublicClient()(*bool)
    GetKeyCredentials()([]KeyCredentialable)
    GetLogo()([]byte)
    GetNotes()(*string)
    GetOnPremisesPublishing()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetOptionalClaims()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetOwners()([]DirectoryObjectable)
    GetParentalControlSettings()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetPasswordCredentials()([]PasswordCredentialable)
    GetPublicClient()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetPublisherDomain()(*string)
    GetRequiredResourceAccess()([]RequiredResourceAccessable)
    GetSamlMetadataUrl()(*string)
    GetServiceManagementReference()(*string)
    GetSignInAudience()(*string)
    GetSpa()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetSynchronization()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetTags()([]string)
    GetTokenEncryptionKeyId()(*string)
    GetTokenIssuancePolicies()([]TokenIssuancePolicyable)
    GetTokenLifetimePolicies()([]TokenLifetimePolicyable)
    GetUniqueName()(*string)
    GetVerifiedPublisher()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetWeb()(IdentitySecurityDefaultsEnforcementPolicyable)
    GetWindows()(IdentitySecurityDefaultsEnforcementPolicyable)
    SetApi(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetAppId(value *string)()
    SetAppManagementPolicies(value []AppManagementPolicyable)()
    SetAppRoles(value []AppRoleable)()
    SetCertification(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetConnectorGroup(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetCreatedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCreatedOnBehalfOf(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetDefaultRedirectUri(value *string)()
    SetDescription(value *string)()
    SetDisabledByMicrosoftStatus(value *string)()
    SetDisplayName(value *string)()
    SetExtensionProperties(value []ExtensionPropertyable)()
    SetFederatedIdentityCredentials(value []FederatedIdentityCredentialable)()
    SetGroupMembershipClaims(value *string)()
    SetHomeRealmDiscoveryPolicies(value []HomeRealmDiscoveryPolicyable)()
    SetIdentifierUris(value []string)()
    SetInfo(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetIsDeviceOnlyAuthSupported(value *bool)()
    SetIsFallbackPublicClient(value *bool)()
    SetKeyCredentials(value []KeyCredentialable)()
    SetLogo(value []byte)()
    SetNotes(value *string)()
    SetOnPremisesPublishing(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetOptionalClaims(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetOwners(value []DirectoryObjectable)()
    SetParentalControlSettings(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetPasswordCredentials(value []PasswordCredentialable)()
    SetPublicClient(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetPublisherDomain(value *string)()
    SetRequiredResourceAccess(value []RequiredResourceAccessable)()
    SetSamlMetadataUrl(value *string)()
    SetServiceManagementReference(value *string)()
    SetSignInAudience(value *string)()
    SetSpa(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetSynchronization(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetTags(value []string)()
    SetTokenEncryptionKeyId(value *string)()
    SetTokenIssuancePolicies(value []TokenIssuancePolicyable)()
    SetTokenLifetimePolicies(value []TokenLifetimePolicyable)()
    SetUniqueName(value *string)()
    SetVerifiedPublisher(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetWeb(value IdentitySecurityDefaultsEnforcementPolicyable)()
    SetWindows(value IdentitySecurityDefaultsEnforcementPolicyable)()
}
